### ISSUE TITLE
JSONDecoder Error in docker

### ISSUE THREAD

**Issue by ShilongGao-Modernatx** [yuyanislearning/MIND#12]
Having this issue when running in docker:

`Traceback (most recent call last):
  File "batch_predict.py", line 265, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "batch_predict.py", line 106, in main
    models.append(tf.keras.models.load_model(FLAGS.pretrain_name+'_fold_'+str(i)))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/save.py", line 187, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 121, in load
    path, options=options, loader_cls=KerasObjectLoader)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py", line 633, in load_internal
    ckpt_options)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 194, in __init__
    super(KerasObjectLoader, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py", line 130, in __init__
    self._load_all()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 215, in _load_all
    self._layer_nodes = self._load_layers()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 315, in _load_layers
    layers[node_id] = self._load_layer(proto.user_object, node_id)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/load.py", line 323, in _load_layer
    metadata = json_utils.decode(proto.metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/saved_model/json_utils.py", line 60, in decode
    return json.loads(json_string, object_hook=_decode_helper)
  File "/usr/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Any help would be appreciated!

**Comment by yuyanislearning** [comment]
Hi, 
Could you provide the full command to run the code?

**Comment by ShilongGao-Modernatx** [comment]
`docker run --gpus all -it --rm -v my/directory/containing/MIND:/workspace yuyanislearning/mind:1.0`
`mkdir temp `
`python batch_predict.py --pretrain_name saved_model/MIND_fifteenfold --data_path  sample/Q5S007.fa --res_path temp --n_fold 15`

**Comment by ShilongGao-Modernatx** [comment]
More info on my system:
Ubuntu 20.04.6, cuda 11.7
If that's helpful

**Comment by yuyanislearning** [comment]
Hi, 
could you try to pull the repo again and retry it from building the docker, which is updated.

**Comment by ShilongGao-Modernatx** [comment]
Hello,
Seems like the issue is fixed. Thank you!
